"""Initial migration.

Revision ID: 34511f58915d
Revises: 
Create Date: 2023-05-28 20:15:22.933146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34511f58915d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('spotify_id', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('spotify_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('spotify_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=120), nullable=False),
    sa.Column('access_token', sa.String(length=120), nullable=False),
    sa.Column('refresh_token', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token'),
    sa.UniqueConstraint('spotify_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spotify_tokens')
    op.drop_table('user')
    # ### end Alembic commands ###
