"""Create TrackPreviews table

Revision ID: 35e0533671ef
Revises: 86cecbe1fd2b
Create Date: 2023-06-26 20:15:47.233199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e0533671ef'
down_revision = '86cecbe1fd2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TrackPreviews',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('url', sa.String(length=240), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Tracks.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TrackPreviews')
    # ### end Alembic commands ###
