"""Initial DB migration

Revision ID: 4ba4facc166c
Revises: 
Create Date: 2023-06-02 20:11:02.162055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba4facc166c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('spotify_id', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('spotify_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('spotify_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(length=120), nullable=False),
    sa.Column('access_token', sa.String(length=256), nullable=False),
    sa.Column('refresh_token', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token'),
    sa.UniqueConstraint('spotify_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spotify_tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
