"""Remove redundant spotify_id column from spotify_tokens

Revision ID: e381845baba9
Revises: 4ba4facc166c
Create Date: 2023-06-12 13:57:28.460472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e381845baba9'
down_revision = '4ba4facc166c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('spotify_tokens_spotify_id_key', type_='unique')
        batch_op.drop_column('spotify_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('spotify_tokens_spotify_id_key', ['spotify_id'])

    # ### end Alembic commands ###
