# name: CI/CD Pipeline

# on:
#   push:
#     branches: [main, cicd]
#     paths-ignore:
#       - "README.md"
#       - "*.txt"
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         # https://github.com/aws-actions/configure-aws-credentials/blob/main/action.yml
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ vars.AWS_REGION }}

#       - name: Login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Build and push Docker image
#         id: docker_build
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           push: true
#           tags: |
#             ${{ steps.login-ecr.outputs.registry }}/songswap-app:latest
#             ${{ steps.login-ecr.outputs.registry }}/songswap-app:${{ github.sha }}
